import json

items = [
  {
    "id": "alien_blaster",
    "name": "Alien Blaster",
    "description": "It goes pew pew. Might disintegrate you if you hold it backward.",
    "emoji": "🔫",
    "type": "Tool",
    "rarity": "Legendary",
    "buy_price": 500000,
    "sell_price": 100000,
    "net_value": 250000,
    "usable": False,
    "usage_info": "A weapon of extraterrestrial origin."
  },
  {
    "id": "half_eaten_burger",
    "name": "Half-Eaten Burger",
    "description": "Still warm. Don't ask where it came from.",
    "emoji": "🍔",
    "type": "Power-up",
    "rarity": "Common",
    "buy_price": 50,
    "sell_price": 10,
    "net_value": 25,
    "usable": True,
    "usage_info": "Restores a tiny bit of health, or gives you food poisoning."
  },
  {
    "id": "ban_hammer",
    "name": "Ban Hammer",
    "description": "The ultimate tool of a power-tripping Discord Mod.",
    "emoji": "🔨",
    "type": "Tool",
    "rarity": "Epic",
    "buy_price": 200000,
    "sell_price": 50000,
    "net_value": 100000,
    "usable": False,
    "usage_info": "Swinging it makes you feel powerful."
  },
  {
    "id": "nft_receipt",
    "name": "NFT Receipt",
    "description": "Proof that you spent way too much money on a JPEG of a monkey.",
    "emoji": "🧾",
    "type": "Junk",
    "rarity": "Rare",
    "buy_price": 0,
    "sell_price": 5,
    "net_value": 5,
    "usable": False,
    "usage_info": "Literally worthless."
  },
  {
    "id": "golden_chalupa",
    "name": "Golden Chalupa",
    "description": "Legend says eating this grants you eternal life, or just extreme indigestion.",
    "emoji": "🌮",
    "type": "Collectable",
    "rarity": "Mythical",
    "buy_price": 0,
    "sell_price": 150000,
    "net_value": 300000,
    "usable": False,
    "usage_info": "A fast-food holy grail."
  },
  {
    "id": "used_bathwater",
    "name": "Used Bathwater",
    "description": "A jar of murky water. It smells like desperation.",
    "emoji": "🫙",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 20000,
    "net_value": 40000,
    "usable": False,
    "usage_info": "Do not drink."
  },
  {
    "id": "backrooms_carpet",
    "name": "Backrooms Carpet",
    "description": "A moist, slightly yellow piece of carpet. It hums quietly.",
    "emoji": "🟨",
    "type": "Collectable",
    "rarity": "Rare",
    "buy_price": 0,
    "sell_price": 15000,
    "net_value": 30000,
    "usable": False,
    "usage_info": "A terrifying souvenir."
  },
  {
    "id": "soundboard",
    "name": "Soundboard",
    "description": "Pre-loaded with copyright music and loud airhorns.",
    "emoji": "🎛️",
    "type": "Tool",
    "rarity": "Uncommon",
    "buy_price": 10000,
    "sell_price": 2000,
    "net_value": 5000,
    "usable": False,
    "usage_info": "Guaranteed to annoy your friends."
  },
  {
    "id": "haunted_mannequin",
    "name": "Haunted Mannequin",
    "description": "It definitely moved when you weren't looking.",
    "emoji": "🧍",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 25000,
    "net_value": 50000,
    "usable": False,
    "usage_info": "Cursed retail prop."
  },
  {
    "id": "waffle_iron",
    "name": "Waffle Iron",
    "description": "A heavy-duty cooking appliance. Doubles as a blunt weapon.",
    "emoji": "🧇",
    "type": "Tool",
    "rarity": "Uncommon",
    "buy_price": 5000,
    "sell_price": 1000,
    "net_value": 2500,
    "usable": False,
    "usage_info": "Makes waffles. Breaks noses."
  },
  {
    "id": "mystery_box",
    "name": "Mystery Box",
    "description": "Bought off the dark web. Probably just contains packing peanuts.",
    "emoji": "📦",
    "type": "Lootbox",
    "rarity": "Rare",
    "buy_price": 50000,
    "sell_price": 10000,
    "net_value": 25000,
    "usable": True,
    "usage_info": "Open at your own risk."
  },
  {
    "id": "reddit_gold",
    "name": "Reddit Gold",
    "description": "Thanks for the gold, kind stranger!",
    "emoji": "🏅",
    "type": "Collectable",
    "rarity": "Uncommon",
    "buy_price": 0,
    "sell_price": 5000,
    "net_value": 10000,
    "usable": False,
    "usage_info": "A useless internet award."
  },
  {
    "id": "arcade_tickets",
    "name": "Arcade Tickets",
    "description": "A massive roll of paper tickets. Worth exactly one plastic spider ring.",
    "emoji": "🎟️",
    "type": "Collectable",
    "rarity": "Common",
    "buy_price": 0,
    "sell_price": 100,
    "net_value": 200,
    "usable": False,
    "usage_info": "Arcade currency."
  },
  {
    "id": "flat_pack_furniture",
    "name": "Flat-Pack Furniture",
    "description": "A box of wooden planks and 400 confusing screws. Good luck.",
    "emoji": "🪑",
    "type": "Tool",
    "rarity": "Rare",
    "buy_price": 20000,
    "sell_price": 4000,
    "net_value": 10000,
    "usable": False,
    "usage_info": "Requires a Ph.D. in Swedish engineering to build."
  },
  {
    "id": "signed_poster",
    "name": "Signed Poster",
    "description": "A poster signed by an obscure anime voice actor. Smells like sweat.",
    "emoji": "📜",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 30000,
    "net_value": 60000,
    "usable": False,
    "usage_info": "A True weeb treasure."
  },
  {
    "id": "lizard_scales",
    "name": "Lizard Scales",
    "description": "Shed from a very prominent tech CEO.",
    "emoji": "🦎",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 40000,
    "net_value": 80000,
    "usable": False,
    "usage_info": "Evidence of the reptilian overlords."
  },
  {
    "id": "union_card",
    "name": "Union Card",
    "description": "A card that terrifies billionaires.",
    "emoji": "🪪",
    "type": "Collectable",
    "rarity": "Rare",
    "buy_price": 0,
    "sell_price": 15000,
    "net_value": 30000,
    "usable": False,
    "usage_info": "Workers of the world, unite!"
  },
  {
    "id": "kitten_ears",
    "name": "Kitten Ears",
    "description": "The quintessential headwear of a Discord mod's favorite user.",
    "emoji": "🐱",
    "type": "Collectable",
    "rarity": "Uncommon",
    "buy_price": 5000,
    "sell_price": 1000,
    "net_value": 2500,
    "usable": False,
    "usage_info": "Meow."
  },
  {
    "id": "vip_badge",
    "name": "VIP Badge",
    "description": "A shiny badge that proves you spent too much money on a streamer.",
    "emoji": "📛",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 25000,
    "net_value": 50000,
    "usable": False,
    "usage_info": "A flex of your disposable income."
  },
  {
    "id": "rug_pull_coin",
    "name": "Rug Pull Coin",
    "description": "A completely worthless cryptocurrency token.",
    "emoji": "📉",
    "type": "Junk",
    "rarity": "Common",
    "buy_price": 0,
    "sell_price": 1,
    "net_value": 1,
    "usable": False,
    "usage_info": "You got scammed."
  },
  {
    "id": "gallon_of_milk",
    "name": "Gallon of Milk",
    "description": "The legendary milk your dad went to the store for 15 years ago.",
    "emoji": "🥛",
    "type": "Collectable",
    "rarity": "Legendary",
    "buy_price": 0,
    "sell_price": 100000,
    "net_value": 200000,
    "usable": False,
    "usage_info": "It's surprisingly not expired."
  },
  {
    "id": "clip_button",
    "name": "Clip Button",
    "description": "Used to immortalize a streamer's biggest fail.",
    "emoji": "🎬",
    "type": "Tool",
    "rarity": "Rare",
    "buy_price": 15000,
    "sell_price": 3000,
    "net_value": 7500,
    "usable": False,
    "usage_info": "Capture the moment."
  },
  {
    "id": "suspicious_rock",
    "name": "Suspicious Rock",
    "description": "A weirdly shiny rock given to you by a local crackhead.",
    "emoji": "🪨",
    "type": "Collectable",
    "rarity": "Uncommon",
    "buy_price": 0,
    "sell_price": 5000,
    "net_value": 10000,
    "usable": False,
    "usage_info": "Might be radioactive."
  },
  {
    "id": "glitched_code",
    "name": "Glitched Code",
    "description": "A fragment of broken code that breaks reality.",
    "emoji": "🧑‍💻",
    "type": "Collectable",
    "rarity": "Mythical",
    "buy_price": 0,
    "sell_price": 500000,
    "net_value": 1000000,
    "usable": False,
    "usage_info": "A speedrunner's dream."
  },
  {
    "id": "ring_light",
    "name": "Ring Light",
    "description": "Essential equipment for any aspiring TikToker.",
    "emoji": "💡",
    "type": "Tool",
    "rarity": "Uncommon",
    "buy_price": 8000,
    "sell_price": 1500,
    "net_value": 4000,
    "usable": False,
    "usage_info": "Perfect lighting."
  },
  {
    "id": "max_level_waifu",
    "name": "Max Level Waifu",
    "description": "A JPEG of a waifu that someone spent their life savings to acquire.",
    "emoji": "💖",
    "type": "Collectable",
    "rarity": "Legendary",
    "buy_price": 0,
    "sell_price": 200000,
    "net_value": 400000,
    "usable": False,
    "usage_info": "Top tier rarity."
  },
  {
    "id": "neon_pet",
    "name": "Neon Pet",
    "description": "A brightly glowing blocky animal. Highly coveted by 9-year-olds.",
    "emoji": "🐶",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 50000,
    "net_value": 100000,
    "usable": False,
    "usage_info": "A status symbol."
  },
  {
    "id": "sigma_grindset_audio",
    "name": "Sigma Grindset Audio",
    "description": "A cassette tape containing 10 hours of uninterrupted phonk music.",
    "emoji": "🎧",
    "type": "Tool",
    "rarity": "Rare",
    "buy_price": 10000,
    "sell_price": 2000,
    "net_value": 5000,
    "usable": False,
    "usage_info": "Stay on the grind."
  },
  {
    "id": "troll_mask",
    "name": "Troll Mask",
    "description": "U mad bro?",
    "emoji": "🎭",
    "type": "Collectable",
    "rarity": "Uncommon",
    "buy_price": 5000,
    "sell_price": 1000,
    "net_value": 2500,
    "usable": False,
    "usage_info": "Problem?"
  },
  {
    "id": "viral_freakout_video",
    "name": "Viral Freakout Video",
    "description": "An HD recording of a Karen completely losing her mind in a store.",
    "emoji": "📹",
    "type": "Collectable",
    "rarity": "Epic",
    "buy_price": 0,
    "sell_price": 35000,
    "net_value": 70000,
    "usable": False,
    "usage_info": "Internet gold."
  }
]

with open("src/config/items.json", "r") as f:
    existing = json.load(f)
existing.extend(items)
with open("src/config/items.json", "w") as f:
    json.dump(existing, f, indent=2)
